// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmxDgkGbI90xq2B5iY5nhajbCV_Kkxqk',
    appId: '1:740898234755:web:91b1055491b78e32ae96b6',
    messagingSenderId: '740898234755',
    projectId: 'shoppo-8a3e0',
    authDomain: 'shoppo-8a3e0.firebaseapp.com',
    storageBucket: 'shoppo-8a3e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SRx3M0uDALWelr6N1tFO2SeD60A14lY',
    appId: '1:740898234755:android:c581df6be998f082ae96b6',
    messagingSenderId: '740898234755',
    projectId: 'shoppo-8a3e0',
    storageBucket: 'shoppo-8a3e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Kr5UIUIFEfZVFDDYGh_-1TOPGdB15cY',
    appId: '1:740898234755:ios:e8abeabfd5597b26ae96b6',
    messagingSenderId: '740898234755',
    projectId: 'shoppo-8a3e0',
    storageBucket: 'shoppo-8a3e0.appspot.com',
    iosClientId: '740898234755-pettlarr1cgc9ifqbvr1cbkfpcg2o2me.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Kr5UIUIFEfZVFDDYGh_-1TOPGdB15cY',
    appId: '1:740898234755:ios:81e12f27174efb05ae96b6',
    messagingSenderId: '740898234755',
    projectId: 'shoppo-8a3e0',
    storageBucket: 'shoppo-8a3e0.appspot.com',
    iosClientId: '740898234755-1ud15ds856t9qmnts6aevemloggfl256.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApplication.RunnerTests',
  );
}
